<div class="comment-block">
<h3 class="open-block required"><?php echo $this->__('Idcard')?> <em style="font-weight: normal;padding: 0 5px 0 0;vertical-align: middle;color: #ff0000;">*</em><span class='expand_plus'></span></h3>
    <div  class="collapse-block ">
	<form id="idcard-form" autocomplete="off">
	    <div class="comment">
	        <div class="comment-form">            
	            <div class="input-box">	              
	              <input class="input-text validate-no-html-tags required-entry" id="customer_comment" name="customer_comment" />
	                <!-- <textarea class="input-text" id="customer_comment" name="customer_comment"></textarea> -->
	            </div>	            
	        </div>
	    </div>
	</form>
	</div>
</div>