<div class="header-v0 header-v2">
	<div class="yt-header-top">
		<div class="container">
			<div class="row">
				
				<div class="col-lg-9 col-md-10 col-sm-9 col-xs-12" style="float:right">
					<div class="yt-header-topv2 hidden-xs">
						<div class="row">
							<div class="col-lg-6 col-md-5 sl-header-text">
								<?php echo $this->getChildHtml('header-slider');?>
							</div>
							<!-- LANGUAGE_CURENCY -->
							<div class="col-lg-6 col-md-7 top-links-action">
								<?php echo $this->getChildHtml('store_language') ?>
								<?php echo $this->getChildHtml('currency'); ?>					
								<div class="block-action-header top-link-account my-account-link">
									<ul>
										<li>
											<a class="account-toplink dropdown-ict" title="<?php echo $this->__('My Account')?>" href="<?php echo $this->getUrl('customer/account')?>"><?php echo $this->__('My Account')?></a>
											<div class="dropdown-link-account">
												<?php echo $this->getChildHtml('topLinks');?>
											</div>
										</li>
									</ul>
								</div>
								<!-- MYLOGIN -->
								<div class="block-action-header top-link-account login-link">
									<ul>
										<?php if(!$this->helper('customer')->isLoggedIn()){?>
										<li>
											<a class="login-btn" data-toggle="modal" data-target="#modal-login" title="<?php echo $this->__('Login')?>"><?php echo $this->__('Login')?></a>
			                                <?php echo $this->getChildHtml('customer_form_mini_login'); ?>
										</li>
										<?php } else{?>
										<li>
											<a class="logout-btn" href="<?php echo $this->getUrl('customer/account/logout')?>" title="<?php echo $this->__('Logout');?>"><?php echo $this->__('Logout');?></a>
			                            </li>
										<?php } ?>
									</ul>
								</div>
								<!-- END LOGIN -->
								
								<div class="action-mobile">

									<div class="block-action-header top-link-account my-account-link account-mobile-btn">
										<ul>
											<li>
												<a class="acc-mobile" title="<?php echo $this->__('My Account')?>" href="<?php echo $this->getUrl('customer/account')?>">&nbsp;</a>
											</li>
										</ul>
										<div class="dropdown-mobile">
											<?php echo $this->getChildHtml('topLinks');?>
										</div>
									</div>
									
									<div class="block-action-header top-link-account login-link login-mobile-btn">
										<ul>
											<?php if(!$this->helper('customer')->isLoggedIn()){?>
											<li>
												<a class="login-btn" href="<?php echo $this->getUrl('customer/account/login')?>" title="<?php echo $this->__('Login')?>">&nbsp;</a>
											</li>
											<?php } else{?>
											<li>
												<a class="logout-btn" href="<?php echo $this->getUrl('customer/account/logout')?>" title="<?php echo $this->__('Logout');?>">&nbsp;</a>
											</li>
											<?php } ?>
										</ul>
									</div>
									
								</div>

							</div>
						</div>
					</div>
					<div class="yt-header-middle">
						
							<div class="row">							
								<div class="col-lg-12 col-md-12 col-sm-12 yt-megamenu">
									<div class="yt-header-under">
										<div class="yt-menu">
											<?php echo $this->getChildHtml('megaMenu') ?>
										</div>

										<div class="dds hidden-lg hidden-md hidden-sm">
											<div class="block-action-header top-link-account my-account-link account-mobile-btn">
												<ul>
													<li>
														<a class="acc-mobile" title="<?php echo $this->__('My Account')?>" href="<?php echo $this->getUrl('customer/account')?>">&nbsp;</a>
													</li>
												</ul>
												<div class="dropdown-mobile">
													<?php echo $this->getChildHtml('topLinks');?>
												</div>
											</div>
											
											<div class="block-action-header top-link-account login-link login-mobile-btn">
												<ul>
													<?php if(!$this->helper('customer')->isLoggedIn()){?>
													<li>
														<a class="login-btn" href="<?php echo $this->getUrl('customer/account/login')?>" title="<?php echo $this->__('Login')?>">&nbsp;</a>
													</li>
													<?php } else{?>
													<li>
														<a class="logout-btn" href="<?php echo $this->getUrl('customer/account/logout')?>" title="<?php echo $this->__('Logout');?>">&nbsp;</a>
													</li>
													<?php } ?>
												</ul>
											</div>
										</div>

										<div class="yt-searchpro">
											<a class="btn-search-mobilev2 icon-search" href="javascript:void(0)" title="<?php echo $this->__('Search')?>"></a>
											<?php echo $this->getChildHtml('searchboxpro'); ?>
											<script>
												jQuery(document).ready(function($){
													$( ".btn-search-mobilev2" ).click(function() {
														$('.form-search').toggleClass('show')
														$(this).toggleClass('active')
													});
												});
											</script>
										</div>
										<div class="mini-cart-header">
											<?php echo $this->getChildHtml('mini-cartpro') ?>
										</div>
										
									</div>
									
								</div>

							</div>
						
					</div>
				</div>
				<div class="col-lg-3 col-md-2 col-sm-3 col-xs-12 logo-wrapper" style="float: left">
					<div class="logo-wrapperv2">
						<h1>
							<a title="<?php echo $this->getLogoAlt() ?>" href="<?php echo $this->getUrl('') ?>">
								<img src="<?php echo $this->getLogoSrc() ?>" alt="<?php echo $this->getLogoAlt() ?>" />
							</a>
						</h1>
					</div>
				</div>
			</div>
			<!-- RESPOSIVE MENU MEGA -->

			<div class="yt-responsivemenu-v2">
				<div id="yt-responsivemenu" class="yt-responsivemenu">
					<?php echo $this->getChildHtml('mobiMenu'); ?>
				</div>	
			</div>		
		</div>
		<!-- END CONTAINER -->
	</div>
	
	

	
</div>
<script type="text/javascript">
	jQuery(document).ready(function($){
		$i = 0;	   
		$('#yt_left .sm_megamenu_wrapper_vertical_menu .sm_megamenu_menu > li.sm_megamenu_lv1').each(function(){
			$this = $(this);
			$i ++; 
			if( $i > 11 ){ 
				$this.css({'display':'none'});
			}  
			if( $i == 11 )  {
				$('#yt_left .sm_megamenu_wrapper_vertical_menu .sm_megamenu_menu').append('<div class="more-wrap"><a href="<?php echo $this->getUrl('all-categories')?>"><?php echo $this->__("All Categories"); ?></div>');
			}
		});
	})
</script>
<style type="text/css">
@media (max-width: 480px) {
	.dds{
		clear: both;
	    position: absolute;
	    top: 73px;
	    right: 96px;
	    width: 120px;
	    height: 47px;
	}
	.header-v0 .yt-header-top .block-action-header{
		height: 47px;
	}
	.header-v0 .yt-header-top .login-link > ul > li > a,
	.header-v0 .account-mobile-btn ul li a.acc-mobile{
		line-height: 46px;
		background-color: #444;
		border-radius: 0 !important;
	    border: none !important;
	    width: 40px;
	    height: 47px;
	    text-align: center;
	}
	.header-v0 .yt-header-top .login-link > ul > li > a.login-btn:before,
	.header-v0 .yt-header-top .login-link > ul > li > a.logout-btn:before,
	.header-v0 .account-mobile-btn ul li .acc-mobile:after{
		color: #999;
		font-size: 16px;
	}
	.header-v0 .yt-header-top .login-link > ul > li > a.login-btn:before{
		margin-right: 0;
	}
	.header-v0 .yt-header-top .top-link-account > ul > li:hover > a,
	.header-v0 .yt-header-top .acc-mobile:hover{
		background-color: #444;
	}
	.header-v0 .yt-header-top .top-link-account > ul > li:hover > a:before,
	.header-v0 .account-mobile-btn ul li .acc-mobile:hover:after{
		color: white;
	}
	.header-v0 .block-action-header.top-link-account.login-link.login-mobile-btn li{
		border:none;
	}
	.header-v0 .yt-header-top .top-link-account > ul > li > a{
		padding: 0;
	}
	.header-v0 .yt-header-top .top-link-account > ul > li{
		margin-top: 0;
	}
	.header-v0 .block-action-header.top-link-account.login-link.login-mobile-btn li{
		padding-top: 0;
	}
	.header-v2 .yt-searchpro .btn-search-mobilev2,
	.header-v2 .mini-cart-header .btn-toggle{
		background-color: transparent !important;
	}
}
</style>