<div class="header-v0 header-v3">
	<div class="yt-header-top">
		<div class="container">
			<div class="row">
				<div id="yt-responsivemenu" class="yt-responsivemenu">
					<?php echo $this->getChildHtml('mobiMenu'); ?>

					<div class="action-mobile">

						<div class="block-action-header top-link-account my-account-link account-mobile-btn">
							<ul class="account-mobile-list">
								<li>
									<a class="login-btn" href="<?php echo $this->getUrl('sales/order/history')?>" title="<?php echo $this->__('My Orders')?>"><?php echo $this->__('My Orders')?></a>
								</li>
								<li class="logoutlink">
									<a class="login-btn cartpr" href="<?php echo $this->getUrl('checkout/cart')?>" title="<?php echo $this->__('My Cart')?>"><?php echo $this->__('My Cart')?> <span class="cart-items"></span></a>
								</li>
								<li class="logoutlink">
									<a href="jacascript::void(0);" class="show-dropdown-mobile" title="<?php echo $this->__('My Account')?>">
										<?php echo $this->__('My Account')?> <i class="icon icon-angle-down" aria-hidden="true"></i>
									</a>
									<div class="dropdown-mobile">
										<?php echo $this->getChildHtml('topLinks');?>
									</div>
								</li>
								<?php if($this->helper('customer')->isLoggedIn()){?>

									<li class="logoutlink">
										<a class="logout-btn" href="<?php echo $this->getUrl('customer/account/logout')?>" title="<?php echo $this->__('Logout');?>">
											<?php echo $this->__('Logout');?>
										</a>
									</li>

								<?php } ?>
							</ul>
						</div>
						
						<div class="block-action-header top-link-account login-link login-mobile-btn">
							<ul class="account-mobile-list">
								<?php if(!$this->helper('customer')->isLoggedIn()){?>
								<li>
									<a class="login-btn" href="<?php echo $this->getUrl('customer/account/login')?>" title="<?php echo $this->__('Login')?>">
										<?php echo $this->__('Login')?>
									</a>
								</li>
								<li>
									<a class="login-btn" href="<?php echo $this->getUrl('customer/account/create')?>" title="<?php echo $this->__('Register')?>"><?php echo $this->__('Register')?></a>
								</li>
								<?php }?>

							</ul>
						</div>
						
					</div>
				</div>
				<div class="col-md-4 sl-header-text">

					<?php echo $this->getChildHtml('header-slider');?>
				</div>
				<!-- LANGUAGE_CURENCY -->
				<div class="col-md-8 top-links-action">
					<?php echo $this->getChildHtml('store_language') ?>
					<?php echo $this->getChildHtml('currency'); ?>					
					<div class="block-action-header top-link-account my-account-link">
						<?php echo $this->getChildHtml('topLinks');?>
						
					</div>
					<!-- MYLOGIN -->
					<div class="block-action-header top-link-account login-link">
						<ul>
							<?php if(!$this->helper('customer')->isLoggedIn()){?>
							<li>
								<a class="login-btn" data-toggle="modal" data-target="#modal-login" title="<?php echo $this->__('Login')?>"><?php echo $this->__('Login')?></a>
                                <?php echo $this->getChildHtml('customer_form_mini_login'); ?>
							</li>
							<li>
								<a class="login-btn" href="<?php echo $this->getUrl('customer/account/create')?>" title="<?php echo $this->__('Register')?>"><?php echo $this->__('Register')?></a>
							</li>
							<?php } ?>

						</ul>
					</div>
					<!-- END LOGIN -->
					
				</div>
			</div>
		</div>
	</div>
	
	<div class="yt-header-middle">
		<div class="container">
			<div class="row">
				<div class="col-lg-3 col-md-2 col-sm-12 logo-wrapper">
					<h1>
						<a title="<?php echo $this->getLogoAlt() ?>" href="<?php echo $this->getUrl('') ?>">
							<img src="<?php echo $this->getLogoSrc() ?>" alt="<?php echo $this->getLogoAlt() ?>" />
						</a>
					</h1>
				</div>
				
				<div class="col-lg-6 col-md-7 col-sm-12 col-xs-12 yt-megamenu">
					<div class="yt-header-under2">
						<div class="yt-menu">
							
							<?php echo $this->getChildHtml('searchboxpro'); ?>
						</div>
						
					</div>
					
				</div>

				<div class="mini-cart-header hidden-xs">
					<?php echo $this->getChildHtml('mini-cartpro') ?>
				</div>

			</div>
		</div>
	</div>

	<div class="yt-header-under-2">
		<div class="container">
			<div class="row yt-header-under-wrap">
				<div class="yt-main-menu col-md-12">
					<div class="header-under-2-wrapper">
						
						<div class="yt-searchbox-vermenu">
							<div class="row">
								<!-- Commented on July 23,2018 -->
								<!-- <div class="col-lg-3 col-md-3">
									<div class="ver-megamenu-header">
											
										 <?php //if( $var_yttheme->getParam('menustyle') == 'mega' ){
							                //echo $this->getLayout()->createBlock('cms/block')->setBlockId('headerv5_ver_config')->toHtml();
							            // } else {
							               // echo $this->getChildHtml('topMenu');
							            // } ?>
									</div>
								</div> -->
								
								<div class="col-lg-12 col-md-12">
									<div class="yt-header-under">
										<div class="yt-menu">
											<?php echo $this->getChildHtml('megaMenu') ?>
										</div>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>