<?php
/*------------------------------------------------------------------------
 # SM Super Categories - Version 1.0.0
 # Copyright (c) 2014 YouTech Company. All Rights Reserved.
 # @license - Copyrighted Commercial Software
 # Author: YouTech Company
 # Websites: http://www.magentech.com
-------------------------------------------------------------------------*/
global $var_yttheme;
$image_base = Mage::getModel('catalog/product')->getSmallImageUrl();
$helper = Mage::helper('supercategories/data');
$cat_info = $this->getListCategoriesFilter();

$list = $this->getListCriterionFilter();

if (!empty($list)) {
	//$sub_cat = Mage::getStoreConfig('supercategories_cfg/source_options/sub_cat_limit');
	$sub_cat = $this->_getConfig('sub_cat_limit');

	$staticID = $this->_getConfig('static_id');

	$autoplay = $this->_getConfig('play');
	
	$stop = $this->_getConfig('stop');
	if($stop=="1"){
		$stop_hover='true';
	}else{
		$stop_hover='false';
	}

	$autoplay = $this->_getConfig('play');
	
	if($autoplay=="1"){
		$play='true';
	}else{
		$play='false';
	}

	$interval = (int)$this->_getConfig('delay');
	$interval = $play ? $interval : 0;
	$speed =(int)$this->_getConfig('duration');
	$start = (int) $this->_getConfig('start');
	$start = ( $start <= 0 || $start > count($list) ) ? 0 : $start - 1;
	$step = (int)$this->_getConfig('scroll',1);
	$step = $step <= 0 ? 1: $step;
	
	$btn = $this->_getConfig('next_prev_display');

	$nb1 = $this->_getConfig('nbi_column1', 4);
	$nb2 = $this->_getConfig('nbi_column2', 3);
	$nb3 = $this->_getConfig('nbi_column3', 2);
	$nb4 = $this->_getConfig('nbi_column4', 2);

	$import_str = "";
	$jsHelper = Mage::helper('core/js');
	// jquery has not added yet
	if (!defined('MAGENTECH_JQUERY') && (int)$this->_getConfig('include_jquery')) {
		// if module allowed jquery.
		$import_str .= $jsHelper->includeSkinScript('sm/supercategories/js/jquery-1.8.2.min.js');
		$import_str .= $jsHelper->includeSkinScript('sm/supercategories/js/jquery-noconflict.js');
		$import_str .= $jsHelper->includeSkinScript('sm/supercategories/js/slider.js');
		define('MAGENTECH_JQUERY', 1);
	}
	echo $import_str;
	$instance = rand() . time();
	$tag_id = 'sm_listing_tabs_' . rand() . time();
	$uniqued ='cat_slider_'.rand().time();
	$class_ltabs = 'ltabs00-' . $this->_getConfig('nbi_column1', 4) . ' ltabs01-' . $this->_getConfig('nbi_column1', 3) . ' ltabs02-' . $this->_getConfig('nbi_column2', 3) . ' ltabs03-' . $this->_getConfig('nbi-column3', 2) . ' ltabs04-' . $this->_getConfig('nbi-column4', 1)
	?>
	<?php $class_respl = 'preset01-' . $this->_getConfig('nb_column1', 4) . ' preset02-' . $this->_getConfig('nb_column2', 3) . ' preset03-' . $this->_getConfig('nb_column3', 2) . ' preset04-' . $this->_getConfig('nb_column4', 2) . ' preset05-' . $this->_getConfig('nb_column5', 1); ?>

	<div id="<?php echo $tag_id; ?>" class="super-category-block super-static-category-block first-load sn-category-block">
		
		<div class="block-title-defaults">
			
			<div class="tab-category-title block-title">
				<strong><span><?php echo $this->_getConfig('category_title_text'); ?></span></strong>
				<!-- <div class="<?php echo $this->_getConfig('category_class'); ?>"></div> -->

				<a class="more" href="<?php echo $cat_info[0]['link'];?>">
					<?php echo $this->_getConfig('view_more_text') ? $this->_getConfig('view_more_text') : $this->_('View More >'); ?>
				</a>
				
			</div>
			
		</div>

		<?php
		$pretext = $this->_getConfig('pretext');
		if (!empty($pretext)) {
			?>
			<div class="pre-text"><?php echo $this->_getConfig('pretext'); ?></div>
		<?php } ?>


		<?php 
			$cms_id = Mage::getSingleton('cms/page')->getIdentifier();
		?>
		
		<!-- <div class="supercat-des">
			<?php //echo $this->getLayout()->createBlock('cms/block')->setBlockId($staticID)->toHtml(); ?>
		</div> -->

		<div class="super-cat-wrapper">
			<div class="overflow-owl-slider">
				<div class="border-cat">
				<div class="rw-margin">
					<div class="ltabs-items-container cat-<?php echo $cat_info[0]['id'];?>"><!--Begin Items-->
						<div class="item item-supercat respl-item static-block-img">
							<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId($staticID)->toHtml(); ?>
						</div>
						<?php foreach ($list as $items) {
							$child_items = isset($items->child) ? $items->child : '';
							$cls_device = $class_ltabs;
							$cls_animate = $this->_getConfig('effect');
							$cls = (isset($items->sel) && $items->sel == "sel") ? ' ltabs-items-selected ltabs-items-loaded' : '';
							$cls .= ($items->id == "*") ? ' items-category-all' : ' items-category-' . $items->id;
							?>
								<?php include('default_items.php'); ?>

						<?php } ?>
					</div>
				</div>
				
				</div>
			</div>
			
		</div>

		
		<?php
		$posttext = $this->_getConfig('posttext');
		if (!empty($posttext)) {
			?>
			<div class="post-text"><?php echo $this->_getConfig('posttext'); ?></div>
		<?php } ?>
	</div>
<?php
} else {
	echo 'Has no item to show!';
} ?>



