<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
        <meta name="viewport" content="initial-scale=1.0, width=device-width" />
        <title><?php echo $this->__('Redirect to Alipay'); ?></title>
        <style>
            .container {
                font-family: Tahoma,Verdana,Arial;
                font-size: 13px;
                margin:0 auto;
                width: 100%;
            }

            .container p {
                border: 1px solid #efefef;
                width: 50%;
                vertical-align: middle;
                padding: 15px;
                text-align: center;
                margin:0 auto;
                margin-top: 45px;
            }

            .container img {
                vertical-align: middle;
            }
        </style>
    </head>
    <body>
        <div class="container">
            <p>
                <img alt="" src="<?php echo $this->getSkinUrl('alipaymate/alipay/redirect.gif', array('_secure'=>true)); ?>" />&nbsp;&nbsp;
                <?php echo $this->__('You will be redirected to the Alipay website in a few seconds ...'); ?>
            </p>

            <?php $alipay = $this->getAlipay(); ?>
            
            <form name="alipaysubmit" id="alipaysubmit" method="post" action="<?php echo $alipay->getAlipayUrl(); ?>">
                <?php echo $alipay->createRequestHtml(); ?>
            </form>
        </div>

        <script type="text/javascript">
            document.getElementById("alipaysubmit").submit();
        </script>
    </body>
</html>