<?php
/*------------------------------------------------------------------------
 # SM Listing Tabs - Version 2.0.1
 # Copyright (c) 2014 YouTech Company. All Rights Reserved.
 # @license - Copyrighted Commercial Software
 # Author: YouTech Company
 # Websites: http://www.magentech.com
-------------------------------------------------------------------------*/
$category_image_config = array(
	'width' => (int)$this->_getConfig('imgcfgcat_width', 50),
	'height' => $this->_getConfig('imgcfgcat_height', 50),
	'constrainOnly' => (bool)$this->_getConfig('imgcfgcat_constrainOnly'),
	'keepAspectRatio' => (bool)$this->_getConfig('imgcfgcat_keepAspectRatio'),
	'keepFrame' => (bool)$this->_getConfig('imgcfgcat_keepFrame'),
	'keepTransparency' => (bool)$this->_getConfig('imgcfgcat_keepTransparency'),
	'background' => (string)$this->_getConfig('imgcfgcat_background'),
	'function' => (int)$this->_getConfig('imgcfgcat_function', 0)
);
?>
<?php $i=0 ?>
<div class="ltabs-tabs-wrap block-title-v2">
	<span class='ltabs-tab-selected'></span>
	<span class='ltabs-tab-arrow'></span>
	<ul class="ltabs-tabs cf">
		<?php
		foreach ($list as $tab) {
			if ($this->_getConfig('filter_type') == "categories") {
				?>
				<li class="ltabs-tab <?php  echo  $this->__('sn').$i++?> <?php echo isset($tab->sel) ? '  tab-sel tab-loaded' : ''; ?> <?php echo ($tab->id == ('*')) ? ' tab-all' : ''; ?>"
				    data-category-id="<?php echo $tab->id; ?>"
				    data-active-content=".items-category-<?php echo ($tab->id == "*") ? 'all' : $tab->id; ?>">
				    <span class="ltabs-tab-label"><?php echo $helper->truncate($tab->title, $this->_getConfig('cat_title_maxlength')); ?>
					
				</li>
			<?php
			} else {
				?>
				<li class="ltabs-tab <?php echo isset($tab->sel) ? '  tab-sel tab-loaded' : ''; ?> <?php echo ($tab->id == ('*')) ? ' tab-all' : ''; ?>"
				    data-category-id="<?php echo $tab->id; ?>"
				    data-active-content=".items-category-<?php echo $tab->id; ?>">
					<span
						class="ltabs-tab-label">
							<?php $title = $this->getLabel($tab->title); ?>
							<?php echo $helper->truncate($title, $this->_getConfig('cat_title_maxlength')); ?>
					</span>
				</li>
			<?php
			}
		} ?>
	</ul>
</div>
