<?php
/*------------------------------------------------------------------------
 # SM Shop By - Version 1.0
 # Copyright (c) 2014 YouTech Company. All Rights Reserved.
 # @license - Copyrighted Commercial Software
 # Author: YouTech Company
 # Websites: http://www.magentech.com
-------------------------------------------------------------------------*/?>

<?php if ($this->canShowBlock()): ?>
    <?php if (!$this->getRequest()->isAjax()): ?>
    <div class="text-center hidden-lg hidden-md hidden-sm" style="margin-bottom: 15px;">
        <button class="button btn-filter"><span><span><?php echo $this->__('Filter') ?></span></span></button>
    </div>
    <div id="layered-navigation">
    <?php endif; ?>
         <div class="block-title">
            <strong><span><?php echo $this->__('Shop by') ?></span></strong>
        </div>
        <div class="block block-layered-nav">
           
            <?php echo $this->getStateHtml() ?>
            <div class="block-content">
				
                <?php if ($this->getLayer()->getState()->getFilters()): ?>
                    <div class="actions"><a class="clear-fillter" href="<?php echo $this->getClearUrl() ?>"><?php echo $this->__('Clear All') ?></a></div>
                <?php endif; ?>
				
                <?php if ($this->canShowOptions()): ?>
                    <!--<p class="block-subtitle"><?php echo $this->__('Shopping Options') ?></p>-->
                    <dl id="narrow-by-list">
                        <?php $_filters = $this->getFilters(); ?>
						<?php $i=0;?>
                        <?php foreach ($_filters as $_filter): ?>
                            <?php if ($_filter->getItemsCount()): $i++;?>
								<div class="filter-wrapp <?php echo $this->__($_filter->getName()) ?>">
									<dt class="<?php echo $this->__($_filter->getName()) ?>"><span><?php echo $this->__($_filter->getName()) ?></span></dt>
									<dd class="scroll-<?php echo $i;?>"><?php echo $_filter->getHtml() ?></dd>
								</div>
                            <?php endif; ?>
                        <?php endforeach; ?>
							
						
                    </dl>
					
                    <script type="text/javascript">decorateDataList('narrow-by-list')</script>
                <?php endif; ?>
				<!--
                <?php if ($this->getLayer()->getState()->getFilters()): ?>
                    <div class="actions"><a href="<?php echo $this->getClearUrl() ?>"><?php echo $this->__('Clear All') ?></a></div>
                <?php endif; ?>
				-->
            </div>
        </div>
		<?php
			$dr = Mage::getStoreConfig('shoppy_cfg/general/direction');
			//var_dump($dr);
		?>
		<script>
		</script>
    <?php if (!$this->getRequest()->isAjax()): ?>
    </div>
	
    <?php endif; ?>
	
	<?php if($this->getRequest()->isAjax()==true) {?>
		<script>
		</script>
	<?php } ?>
<?php endif; ?>

<script type="text/javascript">
    jQuery(document).ready(function($){
        jQuery(".btn-filter").on('click', function(event) {
            jQuery("#layered-navigation").toggle();
        });
    });
</script>
